name: pysen auto lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    linter:
        name: lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7]
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}

          - name: Install pipenv
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements_dev.txt

          - name: Run lint
            run: pysen run lint
